# https://github.com/psf/black/blob/main/.pre-commit-hooks.yaml
- id: pyleft
  name: pyleft
  description: "Python type annotation existence checker"
  entry: pyleft
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python]