name: Pre-Commit Update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 1 * *

jobs:
  auto-update:
    permissions:
      contents: read
      pull-requests: write

    uses: NathanVaughn/reusable-actions/.github/workflows/pre-commit-update.yml@main